### ISSUE TITLE
为什么使用单例模式

### ISSUE THREAD

**Issue by wangzhaohe** [Skycrab/wzhifuSDK#2]
我正在学习，请问为什么要使用单例模式？

**Comment by Skycrab** [comment]
因为不管是UrllibClient，还是CurlClient只需要一个就够了，所以它们是单例的，而HttpClient只是提供了
可配置的获取UrllibClient单例实例的方式，我把HttpClient称为可配置单例。
当然你可以在全局新建一个，但是用单例就让该模块没有任何导入负担，只有在使用时才会实例化。

**Comment by wangzhaohe** [comment]
谢谢答复！
