### ISSUE TITLE
For __init__ in class

### ISSUE THREAD

**Issue by lindylin1817** [Skycrab/wzhifuSDK#3]
You need to add "_args, *_kwargs" in your **init**(self). Otherwise, it will have error in Django.

class NativeLink_pub(Common_util_pub):
    """静态链接二维码"""

```
url = None #静态链接

def __init__(self, *args, **kwargs):
    self.parameters = {} #静态链接参数
```

**Comment by Skycrab** [comment]
can you show how you use?
