### ISSUE TITLE
Provide the demo or document

### ISSUE THREAD

**Issue by tobegit3hub** [Skycrab/wzhifuSDK#7]
The script looks good but we still need demo or document to use that.

It would be great to add more introduction about your project and usage.

**Comment by Skycrab** [comment]
See also [https://github.com/Skycrab/weixin-knife ](url).
The best document is weixin develolper document [https://mp.weixin.qq.com/wiki/home/index.html](url).

**Comment by tobegit3hub** [comment]
Linking to another project could not help. They are two projects and surely the usages(API calls) are different.

The weixin official document is good but not good enough. It needs to get access token and generate signature by ourselves. And that's why you make this project to simplify the processes. You have implemented some helper functions and why not write a demo to tell how to use them?

**Comment by tobegit3hub** [comment]
BTW, the example in [weixin-knife](https://github.com/Skycrab/weixin-knife/tree/master/example/django_example) could not work, maybe because of the older version of Django.

```
➜  django_example git:(master) python ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 2, in <module>
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
```

**Comment by Skycrab** [comment]
I'am sorry,because if provide a demo,it needs depends on web framework,like django or flask,but i want to keep this sdk simple. 
Actually, this sdk's usage is the same to weixin php demo, the class name,and the function name and parameter is the same, this is one reason why this is no python demo.
this is weixin provide php demo

```
    //使用jsapi接口
    $jsApi = new JsApi_pub();

    //=========步骤1：网页授权获取用户openid============
    //通过code获得openid
    if (!isset($_GET['code']))
    {
        //触发微信返回code码
        $url = $jsApi->createOauthUrlForCode(WxPayConf_pub::JS_API_CALL_URL);
        Header("Location: $url"); 
    }else
    {
        //获取code码，以获取openid
        $code = $_GET['code'];
        $jsApi->setCode($code);
        $openid = $jsApi->getOpenId();
    }
```

the python code(simplify)

```
jsApi = JsApi_pub()
url = jsApi.createOauthUrlForCode(WxPayConf_pub.JS_API_CALL_URL)
......
```

**Comment by Skycrab** [comment]
The weixin-knife demo use django 1.3.7, very old version, i am very sorry. Already update the readme, thank you.

**Comment by tobegit3hub** [comment]
Providing the example project is not conflict with keeping it simple. You can provide the django demo or flask demo and any one could know how to use it and extend it.

Now I'm not sure if this script works or not because it lacks document to configure it and use it. If you have any document or example, I can try it soon and integrated with my projects. That's how open-source works instead of putting the code public without maintenance or tutorial.

Anyway, the weixin-knife could not work for the latest django and that's something your should fix.  I could help if you want but at first, I should make sure this script actually works for current version of weixin APIs.

**Comment by tobegit3hub** [comment]
Thanks for re-open this. I have tried the script but get "chooseWXPay:fail". Maybe the signature algorithm has change. Do you mind looking at https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_3 ?

**Comment by Skycrab** [comment]
The signature algorithm has not change.  If the signature is error, will promot error message in the weixin debug mode.  In most cases, is the configuration error. 
It has been a year since I study weixin develop, so much has been forgotten,O(∩_∩)O.

**Comment by tobegit3hub** [comment]
Thanks @Skycrab . The signature is right and I have verify in the weixin's website. Now the script could work and we have used for our website. 👍  I would like to close this and feel free  to provide another demo about this project.

**Comment by Skycrab** [comment]
Thans for your recognition. I do not do well on the document and demo, very sorry.
In programming, you are my idol, O(∩_∩)O.
